# Generated by Django 2.1.7 on 2019-03-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20190329_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/upload/')),
                ('price', models.IntegerField()),
                ('save', models.IntegerField()),
            ],
        ),
    ]
