# Generated by Django 2.1.7 on 2019-03-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20190331_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('massege', models.TextField(max_length=1000)),
            ],
        ),
    ]
